config/routes.rb
Rails.application.routes.draw do
  resources :signins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "signins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/signin.rb
class Signin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/signins_controller.rb
class SigninsController < ApplicationController
  before_action :set_signin, only: %i[ show edit update destroy ]

  # GET /signins or /signins.json
  def index
    @signins = Signin.all
  end

  # GET /signins/1 or /signins/1.json
  def show
  end

  # GET /signins/new
  def new
    @signin = Signin.new
  end

  # GET /signins/1/edit
  def edit
  end

  # POST /signins or /signins.json
  def create
    @signin = Signin.new(signin_params)

    respond_to do |format|
      if @signin.save
        format.html { redirect_to signin_url(@signin), notice: "Signin was successfully created." }
        format.json { render :show, status: :created, location: @signin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @signin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signins/1 or /signins/1.json
  def update
    respond_to do |format|
      if @signin.update(signin_params)
        format.html { redirect_to signin_url(@signin), notice: "Signin was successfully updated." }
        format.json { render :show, status: :ok, location: @signin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @signin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signins/1 or /signins/1.json
  def destroy
    @signin.destroy

    respond_to do |format|
      format.html { redirect_to signins_url, notice: "Signin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signin
      @signin = Signin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def signin_params
      params.require(:signin).permit(:name, :company, :purpose)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signins_helper.rb
module SigninsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/signins/_form.html.erb
<%= form_with(model: signin) do |form| %>
  <% if signin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(signin.errors.count, "error") %> prohibited this signin from being saved:</h2>

      <ul>
        <% signin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :company, style: "display: block" %>
    <%= form.text_field :company %>
  </div>

  <div>
    <%= form.label :purpose, style: "display: block" %>
    <%= form.text_field :purpose %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/signins/_signin.html.erb
<div id="<%= dom_id signin %>">
  <p>
    <strong>Name:</strong>
    <%= signin.name %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= signin.company %>
  </p>

  <p>
    <strong>Purpose:</strong>
    <%= signin.purpose %>
  </p>

</div>

app/views/signins/edit.html.erb
<h1>Editing signin</h1>

<%= render "form", signin: @signin %>

<br>

<div>
  <%= link_to "Show this signin", @signin %> |
  <%= link_to "Back to signins", signins_path %>
</div>

app/views/signins/index.html.erb
<p id="notice"><%= notice %></p>


<head>
<title>Host Logbook</title>
<meta charset="utf-8">


<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<div class="container text-center">

      <div class="jumbotron" align="center">
      <br>
      <br>
      <h2>Host Logbook<h2/>  
      <h4><%= Time.now.strftime("%m/%d/%Y") %></h4>
       
                      
      </div>
      
      
      
      <%= link_to 'Sign In' , new_signin_path, class: "btn btn-success btn-lg btn-block text-white" %>
      <br>
      <br>
      <div class="container text-center">
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
          <tr>
            <th>Name</th>
            <th>Company</th>
            <th>Purpose</th>
          </tr>
        </thead>

        <tbody>
          <% @signins.each do |signin| %>
            <tr>
              <td><%= link_to signin.name , edit_signin_path(signin), class: "text-dark"%></td>
              <td><%= signin.company %></td>
              <td><%= signin.purpose %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

</div>
      <p>
      _________________________________________
    
    </p>
</div>

app/views/signins/new.html.erb
<h1>New signin</h1>

<%= render "form", signin: @signin %>

<br>

<div>
  <%= link_to "Back to signins", signins_path %>
</div>

app/views/signins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @signin %>

<div>
  <%= link_to "Edit this signin", edit_signin_path(@signin) %> |
  <%= link_to "Back to signins", signins_path %>

  <%= button_to "Destroy this signin", @signin, method: :delete %>
</div>